"""migration_payments

Revision ID: 424c565c8e33
Revises: aa13d3b4f33b
Create Date: 2024-06-14 15:18:21.048439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424c565c8e33'
down_revision = 'aa13d3b4f33b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('status_payment_investor', sa.String(length=50), nullable=True))
    op.add_column('user_account', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'is_admin')
    op.drop_column('payment', 'status_payment_investor')
    # ### end Alembic commands ###
