"""profits

Revision ID: 7f7f5ff6fc32
Revises: 424c565c8e33
Create Date: 2024-06-23 17:35:53.807191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7f5ff6fc32'
down_revision = '424c565c8e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('bank_profit', sa.Float(), nullable=True))
    op.add_column('loan', sa.Column('investor_profit', sa.Float(), nullable=True))
    op.add_column('payment', sa.Column('bank_profit', sa.Float(), nullable=True))
    op.add_column('payment', sa.Column('investor_profit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'investor_profit')
    op.drop_column('payment', 'bank_profit')
    op.drop_column('loan', 'investor_profit')
    op.drop_column('loan', 'bank_profit')
    # ### end Alembic commands ###
