"""migration_final_simulation

Revision ID: aa13d3b4f33b
Revises: c79b0938ea4b
Create Date: 2024-05-20 15:39:21.439193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa13d3b4f33b'
down_revision = 'c79b0938ea4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank',
    sa.Column('bank_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('juros_emprestimo', sa.Float(), nullable=False),
    sa.Column('juros_consortium', sa.Float(), nullable=False),
    sa.Column('juros_financiamento', sa.Float(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('bank_id')
    )
    op.create_table('borrower',
    sa.Column('borrower_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('borrower_id')
    )
    op.create_table('consortium_simulation',
    sa.Column('simulation_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('monthly_contribution', sa.Float(), nullable=False),
    sa.Column('duration_months', sa.BigInteger(), nullable=False),
    sa.Column('bank_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.bank_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('simulation_id')
    )
    op.create_table('financing_simulation',
    sa.Column('simulation_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('down_payment', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('duration_months', sa.BigInteger(), nullable=False),
    sa.Column('monthly_payment', sa.Float(), nullable=False),
    sa.Column('bank_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.bank_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('simulation_id')
    )
    op.create_table('investor',
    sa.Column('investor_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('investor_id')
    )
    op.create_table('loan_simulation',
    sa.Column('simulation_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('duration_months', sa.BigInteger(), nullable=False),
    sa.Column('monthly_payment', sa.Float(), nullable=False),
    sa.Column('bank_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.bank_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('simulation_id')
    )
    op.create_table('loan',
    sa.Column('loan_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('borrower_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('duration', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('goals', sa.Enum('viagem', 'compras', 'negocios', name='loan_objective'), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower.borrower_id'], ),
    sa.PrimaryKeyConstraint('loan_id')
    )
    op.create_table('risk_profile',
    sa.Column('profile_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('borrower_id', sa.BigInteger(), nullable=False),
    sa.Column('risk_score', sa.BigInteger(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower.borrower_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('contract',
    sa.Column('contract_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('loan_id', sa.BigInteger(), nullable=False),
    sa.Column('investor_id', sa.BigInteger(), nullable=False),
    sa.Column('borrower_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('date_signed', sa.DateTime(), nullable=False),
    sa.Column('investor_signature_digital_uuid', sa.String(length=36), nullable=True),
    sa.Column('borrower_signature_digital_uuid', sa.String(length=36), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower.borrower_id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['investor.investor_id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.loan_id'], ),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_table('investment',
    sa.Column('investment_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('loan_id', sa.BigInteger(), nullable=False),
    sa.Column('investor_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investor.investor_id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.loan_id'], ),
    sa.PrimaryKeyConstraint('investment_id')
    )
    op.create_table('payment',
    sa.Column('payment_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('loan_id', sa.BigInteger(), nullable=False),
    sa.Column('borrower_id', sa.BigInteger(), nullable=False),
    sa.Column('installment_number', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower.borrower_id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.loan_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.add_column('user_account', sa.Column('telephone', sa.String(length=20), nullable=False))
    op.add_column('user_account', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('user_account', sa.Column('monthly_income', sa.Float(), nullable=False))
    op.add_column('user_account', sa.Column('birth_date', sa.Date(), nullable=False))
    op.add_column('user_account', sa.Column('cpf', sa.String(length=11), nullable=False))
    op.add_column('user_account', sa.Column('pix_key', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'pix_key')
    op.drop_column('user_account', 'cpf')
    op.drop_column('user_account', 'birth_date')
    op.drop_column('user_account', 'monthly_income')
    op.drop_column('user_account', 'name')
    op.drop_column('user_account', 'telephone')
    op.drop_table('payment')
    op.drop_table('investment')
    op.drop_table('contract')
    op.drop_table('risk_profile')
    op.drop_table('loan')
    op.drop_table('loan_simulation')
    op.drop_table('investor')
    op.drop_table('financing_simulation')
    op.drop_table('consortium_simulation')
    op.drop_table('borrower')
    op.drop_table('bank')
    # ### end Alembic commands ###
